---
abstract: 'numeric tests for perl scalars'
author:
  - 'chocolateboy <chocolate@cpan.org>, Michael G. Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-Util-Numeric
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008000
resources:
  bugtracker: https://github.com/chocolateboy/Scalar-Util-Numeric/issues
  repository: https://github.com/chocolateboy/Scalar-Util-Numeric
version: 0.40
