--- #YAML:1.0
name:               Scalar-Util-Numeric
version:            0.11
abstract:           numeric tests for Perl scalars
author:
    - chocolateboy <chocolate@cpan.org>, Michael G Schwern <schwern@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  http://github.com/schwern/Scalar-Util-Numeric
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
